name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "we will look into this issue ASAP ⏫"
        pr-message: "Thank you for your interest in this project❤️ , we will review you PR ASAP ⏫"
